server:
  port: 9297
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/pblgllgs/config-service-jwt-api-gateway.git